### ISSUE TITLE
Problem with tool

### ISSUE THREAD

**Issue by EugenMueller99** [ChrisHughes/chitu-image-tool#1]
Hello Chris, 
can't create a new Boot Logo with this tool.
>>> chitu-image-tool.py encode <C:\Python34\Drucker.jpg><C:\Python34\Druckerxy.logo>
  File "<stdin>", line 1
    chitu-image-tool.py encode <C:\Python34\Drucker.jpg><C:\Python34\Druckerxy.logo>
                             ^
SyntaxError: invalid syntax
What's the problem?

thank you!

**Comment by EugenMueller99** [comment]
cmd console
C:\Users\beds>C:\Python34\chitu-image-tool.py encode "C:\Python34\Drucker.jpg" "C:\Python34\Druckerxy.logo"
Traceback (most recent call last):
  File "C:\Python34\chitu-image-tool.py", line 284, in <module>
    subparsers = parser.add_subparsers(dest='action', required=True, help='Action to perform')
  File "C:\Python34\lib\argparse.py", line 1690, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

**Comment by EugenMueller99** [comment]
with Python 3.8 + Pillow-7.2.0-cp38-cp38-win_amd64
c:\Python>chitu-image-tool.py encode "C:\Python\Drucker.jpg" "C:\Python\Druckerx.logo"
usage: chitu-image-tool.py [-h] {encode,decode,decode_package,encode_package} ...
chitu-image-tool.py: error: the following arguments are required: action

**Comment by ChrisHughes** [comment]
You might need to try with a more python-friendly command line tool on Windows, such as git-bash. It appears to not work properly with python's argparse.

**Comment by EugenMueller99** [comment]
with git same Problem. Test it on 2 notebooks with different Python versions. Same Problem.
![git](https://user-images.githubusercontent.com/71016611/93171746-f38c4f00-f729-11ea-89e4-bb17af5f65d4.jpg)

**Comment by ChrisHughes** [comment]
The issue seems to be with your python environment or setup, python's argparse is a widely accepted standard for handling command line input. Please take a look at the code from line 284 onwards, if argparse cannot handle your command line / bash emulator then you need to reinstall python and ensure you have the correct and official modules available in your pythonpath. I have used this successfully on windows, mac and linux so it is not the OS that is the issue here, it is also not the command line arguments you are using as encode <input> <output> works fine.

**Comment by EugenMueller99** [comment]
Hello Chris,

can you encode a picture for me from your computer? I will support your project with a paypal donate.

Service@Bios-chip24.com
